'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { useRoleGuard } from '@/hooks/useRoleGuard';
import { useSimpul } from '@/context/SimpulContext';
import { Shield, Copy, Check, Link2 } from 'lucide-react';

export default function AuditPage(){
 const user=useRoleGuard(); const {audits,verifyAuditChain}=useSimpul(); const [copied,setCopied]=useState<string|null>(null); const [integrity,setIntegrity]=useState<boolean|null>(null); if(!user)return null;
 const copy=async(h:string,id:string)=>{try{await navigator.clipboard.writeText(h);}catch{}setCopied(id);setTimeout(()=>setCopied(null),1500)};
 return <div className="min-h-screen pb-16 px-4 sm:px-6 max-w-screen-xl mx-auto">
  <div className="pt-6 sm:pt-8 mb-8"><span className="eyebrow">M7 · Governance & Audit</span><h1 className="font-display font-bold text-2xl md:text-3xl mt-1">Audit Trail & Decision Ledger</h1><p className="text-sm mt-1" style={{color:'var(--text-muted)'}}>Setiap perubahan keputusan disimpan bersama actor, state, alasan, timestamp, dan hash berantai.</p></div>
  <div className="card p-5 mb-6 flex flex-wrap gap-6 items-center" style={{border:'1px solid rgba(13,148,136,.2)',background:'rgba(13,148,136,.04)'}}><Shield size={24} style={{color:'#14B8A6'}}/><div><b className="text-sm">SHA-256 hash chain</b><p className="text-xs" style={{color:'var(--text-muted)'}}>Hash setiap record mengikat hash record sebelumnya sehingga urutan ledger dapat diverifikasi.</p></div><button onClick={async()=>setIntegrity(await verifyAuditChain())} className="px-3 py-2 rounded-lg text-xs font-semibold" style={{background:'rgba(37,99,235,.08)',color:'#2563EB',border:'1px solid rgba(37,99,235,.18)'}}>Verify Decision Integrity</button>{integrity!==null&&<span className="text-xs font-semibold" style={{color:integrity?'#0D9488':'#E11D48'}}>{integrity?'VALID CHAIN':'CHAIN ERROR'}</span>}<div className="ml-auto font-mono text-2xl" style={{color:'#14B8A6'}}>{audits.length}<span className="text-xs ml-1">records</span></div></div>
  <div className="space-y-3">{audits.map((a,i)=><motion.div key={a.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="card p-4"><div className="flex gap-3"><div className="w-7 h-7 rounded-full flex items-center justify-center shrink-0" style={{background:'rgba(13,148,136,.1)',color:'#0D9488'}}>{i===0?<Shield size={14}/>:<Link2 size={14}/>}</div><div className="flex-1 min-w-0 pr-1"><div className="flex flex-wrap gap-x-2 gap-y-1 items-center"><b className="text-sm break-words">{a.action}</b><span className="text-[10px] px-2 py-1 rounded-full shrink-0" style={{background:'rgba(13,148,136,.08)',color:'#0D9488'}}>{a.decision}</span></div><span className="block text-[11px] mt-0.5" style={{color:'var(--text-dim)'}}>{new Date(a.timestamp).toLocaleString('id-ID')}</span><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>{a.actor} · {a.role} · {a.entity}</p><p className="text-xs mt-2 break-words"><b>State:</b> {a.previousState} → {a.newState} · {a.reason}</p><div className="mt-2 p-2 rounded bg-[var(--bg-deep)] text-[10px] font-mono break-all"><span style={{color:'var(--text-dim)'}}>prev: {a.previousHash}</span><br/><span style={{color:'#0D9488'}}>hash: {a.hash}</span></div></div><button onClick={()=>copy(a.hash,a.id)} aria-label="Salin hash" className="p-2 rounded self-start shrink-0">{copied===a.id?<Check size={14} style={{color:'#0D9488'}}/>:<Copy size={14}/>}</button></div></motion.div>)}{!audits.length&&<div className="card p-8 text-center text-sm" style={{color:'var(--text-muted)'}}>Belum ada audit record.</div>}</div>
 </div>;
}
