'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { useRoleGuard } from '@/hooks/useRoleGuard';
import { useSimpul } from '@/context/SimpulContext';
import { calculateScenario } from '@/context/SimpulContext';
import type { SimulationRun } from '@/context/SimpulContext';
import { Play, TrendingUp, TrendingDown, CheckCircle, AlertTriangle, Battery, Ship, Clock3, ShieldCheck } from 'lucide-react';
import { SEA_ROUTES, routeKeyFor, nextSailingDate, formatDateID } from '@/lib/seaTransport';
import { useLiveClock } from '@/lib/liveClock';

const scenarios:Record<string,string>={baseline:'Baseline',demand:'Demand Spike',generation:'Generation Drop',unavailable:'BESS Unavailable',delay:'Transport Delay',disaster:'Disaster'};
export default function SimulationPage(){
 const user=useRoleGuard();
 const router=useRouter();
 const {operationalMicrogrids,operationalBess,runScenario,simulationRuns=[]}=useSimpul();
 const [scenario,setScenario]=useState('baseline'); const [phase,setPhase]=useState<'idle'|'running'|'done'>('idle'); const [step,setStep]=useState(0); const [result,setResult]=useState<SimulationRun|null>(null); const clock=useLiveClock();
 const critical=[...operationalMicrogrids].sort((a,b)=>b.riskScore-a.riskScore)[0];
 if(!user)return null;
 const candidate=operationalBess.filter(b=>b.status==='idle'||b.status==='charging').sort((a,b)=>b.soc+b.soh-a.soc-b.soh)[0];
 const route=candidate&&critical?routeKeyFor(candidate.currentLocation,critical.name.replace('Microgrid ','')):null;
 const steps=[
  {label:'PREDICT',text:`EBT ${critical.currentGeneration} MW vs load ${critical.currentDemand} MW`,icon:AlertTriangle},
  {label:'PRIORITIZE',text:`Composite risk ${critical.riskScore}/100`,icon:AlertTriangle},
  {label:'POSITION',text:`${candidate?.name??'Kandidat BESS'} dipilih dari ranking health/capacity`,icon:Battery},
  {label:'TRANSPORT',text:route?`${SEA_ROUTES[route].label} · ${SEA_ROUTES[route].vessel}`:'Mengecek koridor laut',icon:Ship},
  {label:'PROVE',text:'Static allocation dibandingkan dengan adaptive pre-positioning',icon:ShieldCheck},
 ];
 const execute=async()=>{setPhase('running');setStep(0);for(let i=0;i<steps.length;i++){await new Promise(r=>setTimeout(r,500));setStep(i+1);}const r=runScenario(scenario,critical.id);setResult(r);setPhase('done');};
 const before=result?.before ?? calculateScenario(critical,scenario,false); const after=result?.after ?? calculateScenario(critical,scenario,scenario!=='unavailable');
 const kpis=[['Pemanfaatan EBT','renewableUtilization','up','%'],['Kurtailmen','curtailment','down','%'],['Cakupan Beban Kritis','criticalLoadCoverage','up','%'],['Kesiapan Unit','unitReadiness','up','%'],['Waktu Kesiapan Pasokan','supplyReadinessTime','down',' jam']];
 const nextSailing=route?nextSailingDate(SEA_ROUTES[route],new Date()):null;
 return <div className="min-h-screen pb-16 px-4 sm:px-6 max-w-screen-xl mx-auto">
  <div className="pt-6 sm:pt-8 mb-8"><span className="eyebrow">M6 — Simulasi & Evaluasi Dampak</span><h1 className="font-display font-bold text-2xl md:text-3xl mt-1">Simulation & What-if Engine</h1><p className="text-sm mt-1" style={{color:'var(--text-muted)'}}>Output dihitung dari Digital Twin operasional yang sama dengan Map, Risk, Allocation, dan Shipment.</p></div>
  <div className="card p-5 mb-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-display font-semibold">Scenario Playback — H-21 → H-0</h2><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Target otomatis: {critical.name} · risk {critical.riskScore}/100</p></div>{clock&&<span className="font-mono text-[11px]" style={{color:'var(--text-dim)'}}>{clock.toLocaleString('id-ID')}</span>}</div><div className="grid grid-cols-2 md:grid-cols-6 gap-2 mt-4">{Object.entries(scenarios).map(([id,label])=><button key={id} onClick={()=>{setScenario(id);setPhase('idle');setResult(null);setStep(0)}} className="px-3 py-2 rounded-lg text-xs" style={{background:scenario===id?'rgba(13,148,136,.14)':'var(--bg-card)',color:scenario===id?'#0D9488':'var(--text-muted)',border:'1px solid var(--bg-border)'}}>{label}</button>)}</div>{phase==='idle'&&<button onClick={execute} className="mt-4 px-5 py-3 rounded-xl font-semibold text-sm flex items-center gap-2" style={{background:'linear-gradient(135deg,#0D9488,#14B8A6)',color:'#fff'}}><Play size={15}/> Jalankan {scenarios[scenario]}</button>}</div>
  <div className="card p-5 mb-6"><div className="flex items-center gap-2 mb-4"><Clock3 size={17} style={{color:'#2563EB'}}/><h2 className="font-display font-semibold">Decision Timeline</h2></div><div className="grid md:grid-cols-4 gap-3">{[['H-21','DETECT',`Risk ${critical.riskScore}/100 · Satellite/night-light + citizen signal`],['H-14','MATCH',candidate?`${candidate.name} · SOC ${candidate.soc}% · SOH ${candidate.soh}%`:'Cari kandidat BESS'],['H-10','TRANSPORT',route?`Next sailing ${formatDateID(nextSailing!)}`:'Tidak ada route feasible'],['H-0','READY','Pre-positioning siap sebelum kondisi kritis']].map((x,i)=><div key={x[0]} className="p-3 rounded-xl" style={{background:i===0?'rgba(225,29,72,.07)':'rgba(226,232,232,.3)',border:'1px solid var(--bg-border)'}}><b className="font-mono text-xs" style={{color:i===0?'#E11D48':'#2563EB'}}>{x[0]}</b><div className="text-xs font-semibold mt-1">{x[1]}</div><p className="text-[11px] mt-1" style={{color:'var(--text-muted)'}}>{x[2]}</p></div>)}</div></div>
  <AnimatePresence>{phase==='running'&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="card p-5 mb-6"><h3 className="font-display font-semibold mb-4">Decision engine berjalan</h3>{steps.map((x,i)=>{const I=x.icon;return <div key={x.label} className="flex gap-3 items-center py-2"><div className="w-7 h-7 rounded-full flex items-center justify-center" style={{background:step>i?'rgba(13,148,136,.12)':'var(--bg-border)'}}>{step>i?<CheckCircle size={14} style={{color:'#0D9488'}}/>:<I size={13}/>}</div><div><b className="text-xs">{x.label}</b><p className="text-xs" style={{color:'var(--text-muted)'}}>{x.text}</p></div></div>})}</motion.div>}</AnimatePresence>
  {phase==='done'&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><div className="flex items-center gap-2 mb-4"><CheckCircle size={20} style={{color:'#0D9488'}}/><h2 className="font-display font-semibold">Simulation selesai · {scenarios[scenario]}</h2></div><div className="grid md:grid-cols-2 gap-4 mb-5"><div className="card p-5"><p className="text-xs" style={{color:'var(--text-muted)'}}>STATIC ALLOCATION</p><div className="text-3xl font-mono font-bold mt-2">{before.energyNotServed} MW</div><p className="text-xs">energi tidak terlayani</p></div><div className="card p-5" style={{borderColor:'rgba(13,148,136,.3)'}}><p className="text-xs" style={{color:'var(--text-muted)'}}>SIMPUL ADAPTIVE</p><div className="text-3xl font-mono font-bold mt-2" style={{color:'#0D9488'}}>{after.energyNotServed} MW</div><p className="text-xs">energi tidak terlayani</p></div></div><div className="space-y-3">{kpis.map(([label,key,better,unit])=>{const a=Number((after as unknown as Record<string,number>)[key]??0),b=Number((before as unknown as Record<string,number>)[key]??0),diff=a-b;const positive=better==='up'?diff>0:diff<0;return <div className="card p-4" key={label}><div className="flex items-center"><b className="text-sm">{label}</b><span className="ml-auto flex items-center gap-1 font-mono text-xs" style={{color:positive?'#0D9488':'#E11D48'}}>{positive?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {diff>0?'+':''}{diff.toFixed(1)}{unit}</span></div><div className="grid grid-cols-2 gap-2 mt-3"><div className="p-2 rounded-lg text-center" style={{background:'rgba(225,29,72,.07)'}}><b>{b}{unit}</b><p className="text-[10px]">Static</p></div><div className="p-2 rounded-lg text-center" style={{background:'rgba(13,148,136,.07)'}}><b style={{color:'#0D9488'}}>{a}{unit}</b><p className="text-[10px]">SIMPUL</p></div></div></div>})}</div><div className="mt-5 flex gap-2 flex-wrap"><button onClick={()=>router.push('/map')} className="btn-small">Lihat koridor di Map</button><button onClick={()=>router.push('/audit')} className="btn-small">Verifikasi Audit</button><button onClick={()=>{setPhase('idle');setResult(null)}} className="btn-small">Ulangi</button></div></motion.div>}
  {simulationRuns.length>0&&<div className="card p-5 mt-6"><h2 className="font-display font-semibold mb-3">Simulation Runs</h2>{simulationRuns.slice(0,5).map(r=><div key={r.id} className="flex justify-between py-2 border-b" style={{borderColor:'var(--bg-border)'}}><span className="text-xs">{r.scenario} · {r.microgridId}</span><span className="text-xs font-mono">risk {r.after.risk}/100</span></div>)}</div>}
 </div>;
}
